# Generated by Django 5.1.15 on 2026-05-18 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name_plural": "Job Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full-time", "Full Time"),
                            ("part-time", "Part Time"),
                            ("contract", "Contract"),
                            ("freelance", "Freelance"),
                            ("temporary", "Temporary"),
                            ("internship", "Internship"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry-level", "Entry Level (0-1 year)"),
                            ("junior", "Junior (1-3 years)"),
                            ("mid-level", "Mid Level (3-5 years)"),
                            ("senior", "Senior (5-10 years)"),
                            ("expert", "Expert (10+ years)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("high-school", "High School"),
                            ("diploma", "Diploma"),
                            ("bachelor", "Bachelor's Degree"),
                            ("master", "Master's Degree"),
                            ("phd", "PhD"),
                            ("not-specified", "Not Specified"),
                        ],
                        default="not-specified",
                        max_length=30,
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("Alluri Sitharama Raju", "Alluri Sitharama Raju"),
                            ("Anakapalli", "Anakapalli"),
                            ("Anantapuramu", "Anantapuramu"),
                            ("Annamayya", "Annamayya"),
                            ("Bapatla", "Bapatla"),
                            ("Chittoor", "Chittoor"),
                            (
                                "Dr. B.R. Ambedkar Konaseema",
                                "Dr. B.R. Ambedkar Konaseema",
                            ),
                            ("East Godavari", "East Godavari"),
                            ("Eluru", "Eluru"),
                            ("Guntur", "Guntur"),
                            ("Kakinada", "Kakinada"),
                            ("Krishna", "Krishna"),
                            ("Kurnool", "Kurnool"),
                            ("Nandyal", "Nandyal"),
                            ("Nellore", "Nellore"),
                            ("NTR", "NTR"),
                            ("Palnadu", "Palnadu"),
                            ("Parvathipuram Manyam", "Parvathipuram Manyam"),
                            ("Prakasam", "Prakasam"),
                            ("Srikakulam", "Srikakulam"),
                            (
                                "Sri Potti Sriramulu Nellore",
                                "Sri Potti Sriramulu Nellore",
                            ),
                            ("Sri Sathya Sai", "Sri Sathya Sai"),
                            ("Tirupati", "Tirupati"),
                            ("Visakhapatnam", "Visakhapatnam"),
                            ("Vizianagaram", "Vizianagaram"),
                            ("West Godavari", "West Godavari"),
                            ("YSR Kadapa", "YSR Kadapa"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Telangana", "Telangana"),
                            ("Other", "Other"),
                        ],
                        default="Andhra Pradesh",
                        max_length=100,
                    ),
                ),
                ("city_area", models.CharField(blank=True, max_length=100)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("company_name", models.CharField(max_length=200)),
                ("company_email", models.EmailField(max_length=254)),
                ("company_phone", models.CharField(max_length=20)),
                ("company_website", models.URLField(blank=True)),
                (
                    "skills_required",
                    models.TextField(
                        help_text="Comma-separated list of required skills"
                    ),
                ),
                ("benefits", models.TextField(blank=True)),
                ("application_link", models.URLField(blank=True)),
                ("application_email", models.EmailField(blank=True, max_length=254)),
                ("posted_date", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobs.jobcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("under-review", "Under Review"),
                            ("shortlisted", "Shortlisted"),
                            ("rejected", "Rejected"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("resume_url", models.URLField(blank=True)),
                ("cover_letter", models.TextField(blank=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
                "unique_together": {("job", "applicant")},
            },
        ),
    ]
