# Generated by Django 5.1.15 on 2026-03-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_slug", models.SlugField(max_length=80, unique=True)),
                ("menu_title_te", models.CharField(max_length=200)),
                ("menu_title_en", models.CharField(max_length=200)),
                ("page_title_te", models.CharField(max_length=200)),
                ("page_title_en", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "points_text",
                    models.TextField(
                        blank=True, help_text="Use one line per bullet point."
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "menu_title_en"],
            },
        ),
    ]
