# Generated by Django 5.1.15 on 2026-03-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_aboutpagecontent_youtube_embed_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpagecontent",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image related to this section (Christians, ministry work, etc.)",
                null=True,
                upload_to="core/about/",
            ),
        ),
        migrations.AddField(
            model_name="aboutpagecontent",
            name="pdf",
            field=models.FileField(
                blank=True,
                help_text="Upload a PDF document related to this section.",
                null=True,
                upload_to="core/about/",
            ),
        ),
    ]
