# Generated by Django 5.1.15 on 2026-05-18 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_update_navigation_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Gallery Categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="gallery/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="gallery/thumbnails/"
                    ),
                ),
                ("uploaded_date", models.DateTimeField(auto_now_add=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.gallerycategory",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Gallery Images",
                "ordering": ["sort_order", "-uploaded_date"],
            },
        ),
        migrations.CreateModel(
            name="Prayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "Health & Healing"),
                            ("family", "Family"),
                            ("finances", "Finances"),
                            ("work-study", "Work & Studies"),
                            ("spiritual", "Spiritual Growth"),
                            ("protection", "Protection"),
                            ("gratitude", "Gratitude & Praise"),
                            ("guidance", "Guidance"),
                            ("community", "Community"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("submitted_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prayers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_date"],
            },
        ),
    ]
