# Generated by Django 5.1.15 on 2026-03-13 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="member_id",
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="OTPChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("believer", "Believer"),
                            ("pastor", "Pastor"),
                            ("student", "Student"),
                            ("pastor_association", "Pastor Association"),
                            ("ministry", "Ministries"),
                            ("church", "Church"),
                            ("organization", "Christian Organization / Company"),
                            ("admin", "Admin"),
                        ],
                        max_length=32,
                    ),
                ),
                ("identifier", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=6)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
