# Generated by Django 5.1.15 on 2026-03-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_member_id_otpchallenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpchallenge",
            name="failed_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="request_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
