# Generated by Django 5.1.15 on 2026-03-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("organizer_name", models.CharField(max_length=180)),
                ("estimated_attendance", models.PositiveIntegerField()),
                ("organizer_phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("alluri-sitharama-raju", "Alluri Sitharama Raju"),
                            ("anakapalli", "Anakapalli"),
                            ("anantapur", "Anantapur"),
                            ("bapatla", "Bapatla"),
                            ("chittoor", "Chittoor"),
                            ("east-godavari", "East Godavari"),
                            ("eluru", "Eluru"),
                            ("guntur", "Guntur"),
                            ("kadapa", "Kadapa"),
                            ("kakinada", "Kakinada"),
                            ("krishna", "Krishna"),
                            ("kurnool", "Kurnool"),
                            ("nellore", "Nellore"),
                            ("ntr", "NTR"),
                            ("palnadu", "Palnadu"),
                            ("prakasam", "Prakasam"),
                            ("srikakulam", "Srikakulam"),
                            ("tirupati", "Tirupati"),
                            ("visakhapatnam", "Visakhapatnam"),
                            ("vizianagaram", "Vizianagaram"),
                            ("west-godavari", "West Godavari"),
                        ],
                        max_length=60,
                    ),
                ),
                ("state", models.CharField(max_length=120)),
                ("city_area", models.CharField(blank=True, max_length=120)),
                ("mandal", models.CharField(blank=True, max_length=120)),
                ("village", models.CharField(blank=True, max_length=120)),
                (
                    "meeting_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vbs", "VBS"),
                            ("revival", "ఉద్ధీపన సమావేశాలు"),
                            ("gospel", "సువార్త సమావేశాలు"),
                            ("youth", "యూత్ మీటింగ్స్"),
                            ("leaders", "క్రైస్తవ నాయకుల సమావేశాలు"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "denomination",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("assembly-of-god", "Assembly of God"),
                            ("baptist", "Baptist"),
                            ("bible-mission", "Bible Mission"),
                            ("brethren", "Brethren"),
                            ("church-of-christ", "Church of Christ"),
                            ("csi", "CSI"),
                            ("pentecost", "Pentecost"),
                            ("catholics", "Catholics"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "ministry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("american-baptist-mission", "American Baptist Mission"),
                            ("bible-mission", "Bible Mission"),
                            ("brethren-assembly", "Brethren Assembly"),
                            ("calvary-temple", "Calvary Temple"),
                            ("christ-temple", "Christ Temple"),
                            ("church-of-christ", "Church of Christ"),
                            ("full-gospel-fellowship", "Full Gospel Fellowship"),
                            ("hosanna-ministries", "Hosanna Ministries"),
                        ],
                        max_length=60,
                    ),
                ),
                ("google_map_location", models.URLField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("poster", models.FileField(blank=True, upload_to="meetings/posters/")),
                ("youtube_link", models.URLField(blank=True)),
                ("additional_info", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["start_date", "title"],
            },
        ),
    ]
