# Generated by Django 5.1.15 on 2026-05-18 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstituteCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Institute Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("institute_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "institute_type",
                    models.CharField(
                        choices=[
                            ("college", "College"),
                            ("university", "University"),
                            ("school", "School"),
                            ("training-center", "Training Center"),
                            ("seminary", "Theological Seminary"),
                            ("vocational", "Vocational Institute"),
                            ("coaching", "Coaching Center"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("Alluri Sitharama Raju", "Alluri Sitharama Raju"),
                            ("Anakapalli", "Anakapalli"),
                            ("Anantapuramu", "Anantapuramu"),
                            ("Annamayya", "Annamayya"),
                            ("Bapatla", "Bapatla"),
                            ("Chittoor", "Chittoor"),
                            (
                                "Dr. B.R. Ambedkar Konaseema",
                                "Dr. B.R. Ambedkar Konaseema",
                            ),
                            ("East Godavari", "East Godavari"),
                            ("Eluru", "Eluru"),
                            ("Guntur", "Guntur"),
                            ("Kakinada", "Kakinada"),
                            ("Krishna", "Krishna"),
                            ("Kurnool", "Kurnool"),
                            ("Nandyal", "Nandyal"),
                            ("Nellore", "Nellore"),
                            ("NTR", "NTR"),
                            ("Palnadu", "Palnadu"),
                            ("Parvathipuram Manyam", "Parvathipuram Manyam"),
                            ("Prakasam", "Prakasam"),
                            ("Srikakulam", "Srikakulam"),
                            (
                                "Sri Potti Sriramulu Nellore",
                                "Sri Potti Sriramulu Nellore",
                            ),
                            ("Sri Sathya Sai", "Sri Sathya Sai"),
                            ("Tirupati", "Tirupati"),
                            ("Visakhapatnam", "Visakhapatnam"),
                            ("Vizianagaram", "Vizianagaram"),
                            ("West Godavari", "West Godavari"),
                            ("YSR Kadapa", "YSR Kadapa"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Telangana", "Telangana"),
                            ("Other", "Other"),
                        ],
                        default="Andhra Pradesh",
                        max_length=100,
                    ),
                ),
                ("city_area", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("principal_name", models.CharField(blank=True, max_length=200)),
                ("principal_email", models.EmailField(blank=True, max_length=254)),
                ("principal_phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                (
                    "established_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("student_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "degrees_offered",
                    models.CharField(
                        help_text="Comma-separated degrees offered", max_length=200
                    ),
                ),
                (
                    "specializations",
                    models.TextField(blank=True, help_text="Available specializations"),
                ),
                ("image_url", models.URLField(blank=True)),
                (
                    "affiliation",
                    models.CharField(
                        blank=True,
                        help_text="University/Board affiliation",
                        max_length=200,
                    ),
                ),
                ("posted_date", models.DateTimeField(auto_now_add=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_institutes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="institutes.institutecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
    ]
