# Generated by Django 5.1.15 on 2026-03-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("updates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="updates/news/"),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="youtube_embed_url",
            field=models.URLField(blank=True),
        ),
    ]
