# Generated by Django 5.1.15 on 2026-03-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("updates", "0002_newsarticle_image_newsarticle_youtube_embed_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
