# Generated by Django 5.1.15 on 2026-03-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("updates", "0003_newsarticle_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="category",
            field=models.CharField(
                choices=[
                    ("christian-media", "News related to Christian media"),
                    ("honorarium", "News related to Honorarium, Government schemes"),
                    ("christians", "News related to Christians"),
                    ("general", "General News"),
                    (
                        "medical-council",
                        "News related to Delhi Christian Medical Council",
                    ),
                    ("education", "Education related"),
                    ("training", "Training related"),
                    ("jobs", "Jobs related"),
                    ("health", "Health related"),
                    ("society", "News related to problems in society"),
                    ("dr-joseph", "News about Dr. Joseph Prakash Mosiganti"),
                ],
                default="general",
                help_text="Select the news category",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="newspaper",
            field=models.CharField(
                blank=True,
                choices=[
                    ("andhra-jyothi", "Andhra Jyothi"),
                    ("eenadu", "Eenadu"),
                    ("sakshi", "Sakshi"),
                    ("deccan-chronicle", "Deccan Chronicle"),
                    ("the-hindu", "The Hindu"),
                    ("times-of-india", "Times of India"),
                    ("indian-express", "Indian Express"),
                    ("other", "Other"),
                ],
                help_text="Select the newspaper this news is from",
                max_length=50,
            ),
        ),
    ]
