# Generated by Django 5.1.15 on 2026-05-18 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("harassment", "Harassment"),
                            ("violence", "Violence"),
                            ("discrimination", "Discrimination"),
                            ("persecution", "Persecution"),
                            ("property-damage", "Property Damage"),
                            ("fraud", "Fraud"),
                            ("threat", "Threat"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("under-review", "Under Review"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="reported",
                        max_length=20,
                    ),
                ),
                ("incident_date", models.DateTimeField()),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("Alluri Sitharama Raju", "Alluri Sitharama Raju"),
                            ("Anakapalli", "Anakapalli"),
                            ("Anantapuramu", "Anantapuramu"),
                            ("Annamayya", "Annamayya"),
                            ("Bapatla", "Bapatla"),
                            ("Chittoor", "Chittoor"),
                            (
                                "Dr. B.R. Ambedkar Konaseema",
                                "Dr. B.R. Ambedkar Konaseema",
                            ),
                            ("East Godavari", "East Godavari"),
                            ("Eluru", "Eluru"),
                            ("Guntur", "Guntur"),
                            ("Kakinada", "Kakinada"),
                            ("Krishna", "Krishna"),
                            ("Kurnool", "Kurnool"),
                            ("Nandyal", "Nandyal"),
                            ("Nellore", "Nellore"),
                            ("NTR", "NTR"),
                            ("Palnadu", "Palnadu"),
                            ("Parvathipuram Manyam", "Parvathipuram Manyam"),
                            ("Prakasam", "Prakasam"),
                            ("Srikakulam", "Srikakulam"),
                            (
                                "Sri Potti Sriramulu Nellore",
                                "Sri Potti Sriramulu Nellore",
                            ),
                            ("Sri Sathya Sai", "Sri Sathya Sai"),
                            ("Tirupati", "Tirupati"),
                            ("Visakhapatnam", "Visakhapatnam"),
                            ("Vizianagaram", "Vizianagaram"),
                            ("West Godavari", "West Godavari"),
                            ("YSR Kadapa", "YSR Kadapa"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Telangana", "Telangana"),
                            ("Other", "Other"),
                        ],
                        default="Andhra Pradesh",
                        max_length=100,
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("victim_name", models.CharField(blank=True, max_length=200)),
                ("victim_phone", models.CharField(blank=True, max_length=20)),
                ("victim_email", models.EmailField(blank=True, max_length=254)),
                (
                    "witnesses",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated witness names or contact info",
                    ),
                ),
                (
                    "fir_number",
                    models.CharField(
                        blank=True,
                        help_text="First Information Report number if filed",
                        max_length=100,
                    ),
                ),
                ("police_station", models.CharField(blank=True, max_length=200)),
                (
                    "evidence_attachments",
                    models.TextField(
                        blank=True, help_text="URLs to attached documents/images"
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-incident_date"],
            },
        ),
    ]
