# Generated by Django 5.1.15 on 2026-03-13 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BelieverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("life_goal", models.TextField(blank=True)),
                ("hobbies", models.TextField(blank=True)),
                ("youtube_channel", models.URLField(blank=True)),
                ("additional_information", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="believer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChurchProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("church_name", models.CharField(max_length=200)),
                ("pastor_name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("village", models.CharField(blank=True, max_length=200)),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("Alluri Sitharama Raju", "Alluri Sitharama Raju"),
                            ("Anakapalli", "Anakapalli"),
                            ("Anantapuramu", "Anantapuramu"),
                            ("Annamayya", "Annamayya"),
                            ("Bapatla", "Bapatla"),
                            ("Chittoor", "Chittoor"),
                            (
                                "Dr. B.R. Ambedkar Konaseema",
                                "Dr. B.R. Ambedkar Konaseema",
                            ),
                            ("East Godavari", "East Godavari"),
                            ("Eluru", "Eluru"),
                            ("Guntur", "Guntur"),
                            ("Kakinada", "Kakinada"),
                            ("Krishna", "Krishna"),
                            ("Kurnool", "Kurnool"),
                            ("Nandyal", "Nandyal"),
                            ("Nellore", "Nellore"),
                            ("NTR", "NTR"),
                            ("Palnadu", "Palnadu"),
                            ("Parvathipuram Manyam", "Parvathipuram Manyam"),
                            ("Prakasam", "Prakasam"),
                            ("Srikakulam", "Srikakulam"),
                            (
                                "Sri Potti Sriramulu Nellore",
                                "Sri Potti Sriramulu Nellore",
                            ),
                            ("Sri Sathya Sai", "Sri Sathya Sai"),
                            ("Tirupati", "Tirupati"),
                            ("Visakhapatnam", "Visakhapatnam"),
                            ("Vizianagaram", "Vizianagaram"),
                            ("West Godavari", "West Godavari"),
                            ("YSR Kadapa", "YSR Kadapa"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Telangana", "Telangana"),
                            ("Other", "Other"),
                        ],
                        default="Andhra Pradesh",
                        max_length=100,
                    ),
                ),
                (
                    "year_established",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("ministry_details", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="church_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["church_name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_name", models.CharField(max_length=200)),
                ("founder_name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("Alluri Sitharama Raju", "Alluri Sitharama Raju"),
                            ("Anakapalli", "Anakapalli"),
                            ("Anantapuramu", "Anantapuramu"),
                            ("Annamayya", "Annamayya"),
                            ("Bapatla", "Bapatla"),
                            ("Chittoor", "Chittoor"),
                            (
                                "Dr. B.R. Ambedkar Konaseema",
                                "Dr. B.R. Ambedkar Konaseema",
                            ),
                            ("East Godavari", "East Godavari"),
                            ("Eluru", "Eluru"),
                            ("Guntur", "Guntur"),
                            ("Kakinada", "Kakinada"),
                            ("Krishna", "Krishna"),
                            ("Kurnool", "Kurnool"),
                            ("Nandyal", "Nandyal"),
                            ("Nellore", "Nellore"),
                            ("NTR", "NTR"),
                            ("Palnadu", "Palnadu"),
                            ("Parvathipuram Manyam", "Parvathipuram Manyam"),
                            ("Prakasam", "Prakasam"),
                            ("Srikakulam", "Srikakulam"),
                            (
                                "Sri Potti Sriramulu Nellore",
                                "Sri Potti Sriramulu Nellore",
                            ),
                            ("Sri Sathya Sai", "Sri Sathya Sai"),
                            ("Tirupati", "Tirupati"),
                            ("Visakhapatnam", "Visakhapatnam"),
                            ("Vizianagaram", "Vizianagaram"),
                            ("West Godavari", "West Godavari"),
                            ("YSR Kadapa", "YSR Kadapa"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Telangana", "Telangana"),
                            ("Other", "Other"),
                        ],
                        default="Andhra Pradesh",
                        max_length=100,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("ministry_type", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["organization_name"],
            },
        ),
        migrations.CreateModel(
            name="PastorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pastor_name", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("church_name", models.CharField(max_length=200)),
                ("church_address", models.TextField()),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("Alluri Sitharama Raju", "Alluri Sitharama Raju"),
                            ("Anakapalli", "Anakapalli"),
                            ("Anantapuramu", "Anantapuramu"),
                            ("Annamayya", "Annamayya"),
                            ("Bapatla", "Bapatla"),
                            ("Chittoor", "Chittoor"),
                            (
                                "Dr. B.R. Ambedkar Konaseema",
                                "Dr. B.R. Ambedkar Konaseema",
                            ),
                            ("East Godavari", "East Godavari"),
                            ("Eluru", "Eluru"),
                            ("Guntur", "Guntur"),
                            ("Kakinada", "Kakinada"),
                            ("Krishna", "Krishna"),
                            ("Kurnool", "Kurnool"),
                            ("Nandyal", "Nandyal"),
                            ("Nellore", "Nellore"),
                            ("NTR", "NTR"),
                            ("Palnadu", "Palnadu"),
                            ("Parvathipuram Manyam", "Parvathipuram Manyam"),
                            ("Prakasam", "Prakasam"),
                            ("Srikakulam", "Srikakulam"),
                            (
                                "Sri Potti Sriramulu Nellore",
                                "Sri Potti Sriramulu Nellore",
                            ),
                            ("Sri Sathya Sai", "Sri Sathya Sai"),
                            ("Tirupati", "Tirupati"),
                            ("Visakhapatnam", "Visakhapatnam"),
                            ("Vizianagaram", "Vizianagaram"),
                            ("West Godavari", "West Godavari"),
                            ("YSR Kadapa", "YSR Kadapa"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Telangana", "Telangana"),
                            ("Other", "Other"),
                        ],
                        default="Andhra Pradesh",
                        max_length=100,
                    ),
                ),
                ("years_of_ministry", models.PositiveIntegerField(default=0)),
                ("additional_information", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pastor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["pastor_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("student_name", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("college_name", models.CharField(max_length=200)),
                ("course", models.CharField(max_length=200)),
                ("year_of_study", models.CharField(max_length=100)),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("Alluri Sitharama Raju", "Alluri Sitharama Raju"),
                            ("Anakapalli", "Anakapalli"),
                            ("Anantapuramu", "Anantapuramu"),
                            ("Annamayya", "Annamayya"),
                            ("Bapatla", "Bapatla"),
                            ("Chittoor", "Chittoor"),
                            (
                                "Dr. B.R. Ambedkar Konaseema",
                                "Dr. B.R. Ambedkar Konaseema",
                            ),
                            ("East Godavari", "East Godavari"),
                            ("Eluru", "Eluru"),
                            ("Guntur", "Guntur"),
                            ("Kakinada", "Kakinada"),
                            ("Krishna", "Krishna"),
                            ("Kurnool", "Kurnool"),
                            ("Nandyal", "Nandyal"),
                            ("Nellore", "Nellore"),
                            ("NTR", "NTR"),
                            ("Palnadu", "Palnadu"),
                            ("Parvathipuram Manyam", "Parvathipuram Manyam"),
                            ("Prakasam", "Prakasam"),
                            ("Srikakulam", "Srikakulam"),
                            (
                                "Sri Potti Sriramulu Nellore",
                                "Sri Potti Sriramulu Nellore",
                            ),
                            ("Sri Sathya Sai", "Sri Sathya Sai"),
                            ("Tirupati", "Tirupati"),
                            ("Visakhapatnam", "Visakhapatnam"),
                            ("Vizianagaram", "Vizianagaram"),
                            ("West Godavari", "West Godavari"),
                            ("YSR Kadapa", "YSR Kadapa"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Telangana", "Telangana"),
                            ("Other", "Other"),
                        ],
                        default="Andhra Pradesh",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
