# Generated by Django 5.1.15 on 2026-05-18 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0002_churchprofile_latitude_churchprofile_longitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Leader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("pastor", "Pastor"),
                            ("evangelist", "Evangelist"),
                            ("bishop", "Bishop"),
                            ("apostle", "Apostle"),
                            ("missionary", "Missionary"),
                            ("youth-leader", "Youth Leader"),
                            ("worship-leader", "Worship Leader"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("Alluri Sitharama Raju", "Alluri Sitharama Raju"),
                            ("Anakapalli", "Anakapalli"),
                            ("Anantapuramu", "Anantapuramu"),
                            ("Annamayya", "Annamayya"),
                            ("Bapatla", "Bapatla"),
                            ("Chittoor", "Chittoor"),
                            (
                                "Dr. B.R. Ambedkar Konaseema",
                                "Dr. B.R. Ambedkar Konaseema",
                            ),
                            ("East Godavari", "East Godavari"),
                            ("Eluru", "Eluru"),
                            ("Guntur", "Guntur"),
                            ("Kakinada", "Kakinada"),
                            ("Krishna", "Krishna"),
                            ("Kurnool", "Kurnool"),
                            ("Nandyal", "Nandyal"),
                            ("Nellore", "Nellore"),
                            ("NTR", "NTR"),
                            ("Palnadu", "Palnadu"),
                            ("Parvathipuram Manyam", "Parvathipuram Manyam"),
                            ("Prakasam", "Prakasam"),
                            ("Srikakulam", "Srikakulam"),
                            (
                                "Sri Potti Sriramulu Nellore",
                                "Sri Potti Sriramulu Nellore",
                            ),
                            ("Sri Sathya Sai", "Sri Sathya Sai"),
                            ("Tirupati", "Tirupati"),
                            ("Visakhapatnam", "Visakhapatnam"),
                            ("Vizianagaram", "Vizianagaram"),
                            ("West Godavari", "West Godavari"),
                            ("YSR Kadapa", "YSR Kadapa"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Telangana", "Telangana"),
                            ("Other", "Other"),
                        ],
                        default="Andhra Pradesh",
                        max_length=100,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "organization_name",
                    models.CharField(
                        blank=True, help_text="Church/Organization name", max_length=200
                    ),
                ),
                ("years_in_ministry", models.PositiveIntegerField(default=0)),
                ("biography", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("posted_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leader_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Leaders",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Marriage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("widowed", "Widowed"),
                            ("divorced", "Divorced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("Alluri Sitharama Raju", "Alluri Sitharama Raju"),
                            ("Anakapalli", "Anakapalli"),
                            ("Anantapuramu", "Anantapuramu"),
                            ("Annamayya", "Annamayya"),
                            ("Bapatla", "Bapatla"),
                            ("Chittoor", "Chittoor"),
                            (
                                "Dr. B.R. Ambedkar Konaseema",
                                "Dr. B.R. Ambedkar Konaseema",
                            ),
                            ("East Godavari", "East Godavari"),
                            ("Eluru", "Eluru"),
                            ("Guntur", "Guntur"),
                            ("Kakinada", "Kakinada"),
                            ("Krishna", "Krishna"),
                            ("Kurnool", "Kurnool"),
                            ("Nandyal", "Nandyal"),
                            ("Nellore", "Nellore"),
                            ("NTR", "NTR"),
                            ("Palnadu", "Palnadu"),
                            ("Parvathipuram Manyam", "Parvathipuram Manyam"),
                            ("Prakasam", "Prakasam"),
                            ("Srikakulam", "Srikakulam"),
                            (
                                "Sri Potti Sriramulu Nellore",
                                "Sri Potti Sriramulu Nellore",
                            ),
                            ("Sri Sathya Sai", "Sri Sathya Sai"),
                            ("Tirupati", "Tirupati"),
                            ("Visakhapatnam", "Visakhapatnam"),
                            ("Vizianagaram", "Vizianagaram"),
                            ("West Godavari", "West Godavari"),
                            ("YSR Kadapa", "YSR Kadapa"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Telangana", "Telangana"),
                            ("Other", "Other"),
                        ],
                        default="Andhra Pradesh",
                        max_length=100,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("occupation", models.CharField(blank=True, max_length=200)),
                ("education", models.CharField(blank=True, max_length=200)),
                ("about_me", models.TextField(blank=True)),
                (
                    "interests",
                    models.TextField(blank=True, help_text="Comma-separated interests"),
                ),
                (
                    "looking_for",
                    models.TextField(
                        blank=True,
                        help_text="Describe what you're looking for in a partner",
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                ("phone_visible", models.BooleanField(default=False)),
                ("posted_date", models.DateTimeField(auto_now_add=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marriage_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
    ]
